version: "3.9"

services:
  sts_server:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ALIBABA_CLOUD_ACCESS_KEY_ID=<your_access_key_id>
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET=<your_access_key_secret>
      - ROLE_ARN=<your_role_arn>